'use client';

import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Copy, Download, FileText, Globe, User, Shield, AlertCircle, Check, Image as ImageIcon, Loader2, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.NEXT_PUBLIC_GEMINI_API_KEY! });

interface Rule {
  id: string;
  type: 'Allow' | 'Disallow';
  path: string;
}

interface UserAgent {
  id: string;
  name: string;
  rules: Rule[];
}

const NIKE_SWOOSH = `#                                                                                                    
#                 \`\`                                                                        \`\`\`.\`    
#               \`+/                                                                 \`\`.-/+o+:-.      
#             \`/mo                                                          \`\`.-:+syhdhs/-\`          
#            -hMd                                                    \`..:+oyhmNNmds/-\`               
#          \`oNMM/                                            \`\`.-/oyhdmMMMMNdy+:.                    
#         .hMMMM-                                     \`.-/+shdmNMMMMMMNdy+:.                         
#        :mMMMMM+                             \`.-:+sydmNMMMMMMMMMNmho:.\`                             
#       :NMMMMMMN:                    \`.-:/oyhmmNMMMMMMMMMMMNmho:.\`                                  
#      .NMMMMMMMMNy:\`          \`.-/oshdmNMMMMMMMMMMMMMMMmhs/-\`                                       
#      hMMMMMMMMMMMMmhysooosyhdmNMMMMMMMMMMMMMMMMMMmds/-\`                                            
#     .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+-.\`                                                
#     -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+-.\`                                                     
#     \`NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyo:.\`                                                          
#      /NMMMMMMMMMMMMMMMMMMMMMMMmho:.\`                                                               
#       .yNMMMMMMMMMMMMMMMMmhs/.\`                                                                    
#         ./shdmNNmmdhyo/-\`\`                                                                         
#              \`\`\`\`\`                 `;

export default function RobotsGenerator() {
  const [userAgents, setUserAgents] = useState<UserAgent[]>([
    {
      id: '1',
      name: '*',
      rules: [
        { id: 'r1', type: 'Disallow', path: '/admin' },
        { id: 'r2', type: 'Disallow', path: '/private' },
      ],
    },
  ]);
  const [sitemaps, setSitemaps] = useState<string[]>(['https://example.com/sitemap.xml']);
  const [header, setHeader] = useState('# Generated by Robots.txt Generator Pro');
  const [footer, setFooter] = useState(NIKE_SWOOSH);
  const [copied, setCopied] = useState(false);
  const [isGeneratingAscii, setIsGeneratingAscii] = useState(false);
  const [showPreviewOnMobile, setShowPreviewOnMobile] = useState(false);
  const [seoInsight, setSeoInsight] = useState<string | null>(null);
  const [isGeneratingInsight, setIsGeneratingInsight] = useState(false);
  const fileInputRef = React.useRef<HTMLInputElement>(null);

  const generateAscii = (img: HTMLImageElement) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';

    const width = 80;
    const height = (img.height / img.width) * width * 0.5; // 0.5 to compensate for character aspect ratio
    canvas.width = width;
    canvas.height = height;

    ctx.drawImage(img, 0, 0, width, height);
    const imageData = ctx.getImageData(0, 0, width, height);
    const pixels = imageData.data;

    const chars = '@%#*+=-:. ';
    let ascii = '';

    for (let i = 0; i < pixels.length; i += 4) {
      const r = pixels[i];
      const g = pixels[i + 1];
      const b = pixels[i + 2];
      const a = pixels[i + 3];

      // If transparent, use space
      if (a < 128) {
        ascii += ' ';
      } else {
        const brightness = (r + g + b) / 3;
        const charIndex = Math.floor((brightness / 255) * (chars.length - 1));
        ascii += chars[charIndex];
      }

      if ((i / 4 + 1) % width === 0) {
        ascii += '\n';
      }
    }

    // Add # to each line
    return ascii.split('\n').map(line => line.trim() ? `# ${line}` : '#').join('\n');
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsGeneratingAscii(true);
    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new Image();
      img.onload = () => {
        const ascii = generateAscii(img);
        setFooter(ascii);
        setIsGeneratingAscii(false);
      };
      img.src = event.target?.result as string;
    };
    reader.readAsDataURL(file);
  };

  const generatedText = React.useMemo(() => {
    let text = header ? `${header}\n\n` : '';

    userAgents.forEach((ua) => {
      text += `User-agent: ${ua.name}\n`;
      ua.rules.forEach((rule) => {
        text += `${rule.type}: ${rule.path}\n`;
      });
      text += '\n';
    });

    sitemaps.forEach((sitemap) => {
      text += `Sitemap: ${sitemap}\n`;
    });

    if (footer) {
      text += `\n${footer}`;
    }

    return text;
  }, [userAgents, sitemaps, header, footer]);

  const addUserAgent = () => {
    setUserAgents([
      ...userAgents,
      { id: Math.random().toString(36).substr(2, 9), name: 'New-Agent', rules: [] },
    ]);
  };

  const removeUserAgent = (id: string) => {
    const agent = userAgents.find(ua => ua.id === id);
    if (agent?.name === '*') return;
    setUserAgents(userAgents.filter((ua) => ua.id !== id));
  };

  const updateUserAgentName = (id: string, name: string) => {
    setUserAgents(userAgents.map((ua) => (ua.id === id ? { ...ua, name } : ua)));
  };

  const addRule = (uaId: string) => {
    setUserAgents(
      userAgents.map((ua) => {
        if (ua.id === uaId) {
          return {
            ...ua,
            rules: [
              ...ua.rules,
              { id: Math.random().toString(36).substr(2, 9), type: 'Disallow', path: '/' },
            ],
          };
        }
        return ua;
      })
    );
  };

  const removeRule = (uaId: string, ruleId: string) => {
    setUserAgents(
      userAgents.map((ua) => {
        if (ua.id === uaId) {
          return { ...ua, rules: ua.rules.filter((r) => r.id !== ruleId) };
        }
        return ua;
      })
    );
  };

  const updateRule = (uaId: string, ruleId: string, updates: Partial<Rule>) => {
    setUserAgents(
      userAgents.map((ua) => {
        if (ua.id === uaId) {
          return {
            ...ua,
            rules: ua.rules.map((r) => (r.id === ruleId ? { ...r, ...updates } : r)),
          };
        }
        return ua;
      })
    );
  };

  const addSitemap = () => {
    setSitemaps([...sitemaps, 'https://example.com/sitemap-new.xml']);
  };

  const removeSitemap = (index: number) => {
    setSitemaps(sitemaps.filter((_, i) => i !== index));
  };

  const updateSitemap = (index: number, value: string) => {
    const newSitemaps = [...sitemaps];
    newSitemaps[index] = value;
    setSitemaps(newSitemaps);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const element = document.createElement('a');
    const file = new Blob([generatedText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'robots.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const getGeminiInsight = async () => {
    setIsGeneratingInsight(true);
    try {
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: `Analyze this robots.txt file and provide 2-3 short, professional SEO insights or best practices in a concise list format. Keep it under 50 words total.
        
        File Content:
        ${generatedText}`,
      });
      setSeoInsight(response.text || "No insights available at this time.");
    } catch (error) {
      console.error("Gemini Error:", error);
      setSeoInsight("Failed to generate insights. Please try again.");
    } finally {
      setIsGeneratingInsight(false);
    }
  };

  return (
    <div id="tool" className="min-h-screen bg-[#E4E3E0] text-[#141414] font-sans selection:bg-[#141414] selection:text-[#E4E3E0] relative">
      {/* Mobile Toggle Button */}
      <div className="lg:hidden fixed bottom-6 right-6 z-[60]">
        <button
          onClick={() => {
            const previewElement = document.getElementById('preview-side');
            const editorElement = document.getElementById('editor-side');
            if (showPreviewOnMobile) {
              editorElement?.scrollIntoView({ behavior: 'smooth' });
            } else {
              previewElement?.scrollIntoView({ behavior: 'smooth' });
            }
            setShowPreviewOnMobile(!showPreviewOnMobile);
          }}
          className="bg-[#141414] text-[#E4E3E0] w-14 h-14 rounded-full shadow-2xl flex items-center justify-center border border-[#E4E3E0]/20"
        >
          {showPreviewOnMobile ? <FileText size={20} /> : <Globe size={20} />}
        </button>
      </div>

      <main className="grid grid-cols-1 lg:grid-cols-2 min-h-[calc(100vh-89px)]">
        {/* Editor Side */}
        <div id="editor-side" className="border-b lg:border-b-0 lg:border-r border-[#141414] p-6 lg:p-8 overflow-y-auto lg:max-h-[calc(100vh-89px)]">
          <section className="mb-12">
            <div className="flex items-center justify-between mb-4 border-b border-[#141414] pb-2">
              <h2 className="text-xs uppercase tracking-[0.2em] font-bold flex items-center gap-2">
                <Sparkles size={14} className="text-[#141414]" /> Gemini SEO Insights
              </h2>
              <button
                onClick={getGeminiInsight}
                disabled={isGeneratingInsight}
                className="text-[9px] uppercase font-mono border border-[#141414] px-2 py-0.5 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors flex items-center gap-1 disabled:opacity-50"
              >
                {isGeneratingInsight ? <Loader2 size={10} className="animate-spin" /> : <Sparkles size={10} />}
                Analyze File
              </button>
            </div>
            <div className="bg-[#141414]/5 p-4 border border-dashed border-[#141414]/20 min-h-[60px] flex items-center justify-center">
              {seoInsight ? (
                <p className="text-[11px] font-mono leading-relaxed opacity-80 italic">
                  {seoInsight}
                </p>
              ) : (
                <p className="text-[10px] uppercase font-mono opacity-30 tracking-widest">
                  Click analyze for AI-powered SEO tips
                </p>
              )}
            </div>
          </section>

          <section className="mb-12">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 border-b border-[#141414] pb-2 gap-4">
              <h2 className="text-xs uppercase tracking-[0.2em] font-bold flex items-center gap-2">
                <FileText size={14} /> Global Configuration
              </h2>
              <div className="flex gap-2 w-full sm:w-auto">
                <button
                  onClick={copyToClipboard}
                  className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2 sm:px-3 sm:py-1 border border-[#141414] hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors text-xs sm:text-[10px] font-mono uppercase tracking-wider"
                >
                  {copied ? <Check size={14} /> : <Copy size={14} />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button
                  onClick={downloadFile}
                  className="flex-1 sm:flex-none flex items-center justify-center gap-2 px-4 py-2 sm:px-3 sm:py-1 bg-[#141414] text-[#E4E3E0] hover:bg-[#333] transition-colors text-xs sm:text-[10px] font-mono uppercase tracking-wider"
                >
                  <Download size={14} />
                  Download
                </button>
              </div>
            </div>
            <div className="space-y-4">
              <div>
                <label className="text-[10px] uppercase font-mono opacity-50 block mb-1">Header Comment</label>
                <input
                  type="text"
                  value={header}
                  onChange={(e) => setHeader(e.target.value)}
                  className="w-full bg-transparent border border-[#141414] p-3 font-mono text-sm focus:outline-none focus:ring-1 focus:ring-[#141414]"
                  placeholder="# Enter header comment..."
                />
              </div>
              <div>
                <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-1 gap-2">
                  <label className="text-[10px] uppercase font-mono opacity-50 block">Footer / ASCII Art</label>
                  <div className="flex flex-wrap gap-2">
                    <input
                      type="file"
                      ref={fileInputRef}
                      onChange={handleLogoUpload}
                      accept="image/png,image/jpeg"
                      className="hidden"
                    />
                    <button
                      onClick={() => fileInputRef.current?.click()}
                      disabled={isGeneratingAscii}
                      className="text-[10px] sm:text-[9px] uppercase font-mono border border-[#141414] px-3 py-1.5 sm:px-2 sm:py-0.5 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors flex items-center gap-1 disabled:opacity-50"
                    >
                      {isGeneratingAscii ? <Loader2 size={12} className="animate-spin" /> : <ImageIcon size={12} />}
                      Generate from Logo
                    </button>
                    <button
                      onClick={() => setFooter(NIKE_SWOOSH)}
                      className="text-[10px] sm:text-[9px] uppercase font-mono border border-[#141414] px-3 py-1.5 sm:px-2 sm:py-0.5 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors"
                    >
                      Reset to Nike
                    </button>
                  </div>
                </div>
                <textarea
                  value={footer}
                  onChange={(e) => setFooter(e.target.value)}
                  rows={10}
                  className="w-full bg-transparent border border-[#141414] p-3 font-mono text-xs sm:text-[10px] leading-tight focus:outline-none focus:ring-1 focus:ring-[#141414] resize-none"
                  placeholder="# Enter footer or ASCII art..."
                />
              </div>
            </div>
          </section>

          <section className="mb-12">
            <div className="flex items-center justify-between mb-6 border-b border-[#141414] pb-2">
              <h2 className="text-xs uppercase tracking-[0.2em] font-bold flex items-center gap-2">
                <User size={14} /> User Agents & Rules
              </h2>
              <button
                onClick={addUserAgent}
                className="text-xs sm:text-[10px] uppercase font-mono border border-[#141414] px-3 py-1.5 sm:px-2 sm:py-1 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors flex items-center gap-1"
              >
                <Plus size={12} /> Add Agent
              </button>
            </div>

            <div className="space-y-8">
              <AnimatePresence mode="popLayout">
                {userAgents.map((ua) => (
                  <motion.div
                    key={ua.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="border border-[#141414] p-4 bg-[#E4E3E0] relative group"
                  >
                    {ua.name !== '*' && (
                      <button
                        onClick={() => removeUserAgent(ua.id)}
                        className="absolute top-2 right-2 p-2 text-[#141414]/30 hover:text-red-600 hover:bg-red-50 transition-all rounded-sm z-20"
                        title="Remove Agent"
                      >
                        <Trash2 size={16} />
                      </button>
                    )}
                    <div className="mb-4">
                      <label className="text-[10px] uppercase font-mono opacity-50 block mb-1">User-agent Name</label>
                      <input
                        type="text"
                        value={ua.name}
                        onChange={(e) => updateUserAgentName(ua.id, e.target.value)}
                        className="w-full bg-transparent border-b border-[#141414] pb-1 font-bold text-lg focus:outline-none"
                        placeholder="*"
                      />
                    </div>

                    <div className="space-y-2">
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-[10px] uppercase font-mono opacity-50">Directives</span>
                        <button
                          onClick={() => addRule(ua.id)}
                          className="text-[10px] sm:text-[9px] uppercase font-mono border border-[#141414] px-2 py-1 sm:px-1.5 sm:py-0.5 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors"
                        >
                          + Add Rule
                        </button>
                      </div>
                      {ua.rules.map((rule) => (
                        <div key={rule.id} className="flex flex-wrap sm:flex-nowrap gap-2 items-center">
                          <select
                            value={rule.type}
                            onChange={(e) => updateRule(ua.id, rule.id, { type: e.target.value as any })}
                            className="w-full sm:w-auto bg-transparent border border-[#141414] p-2 sm:p-1 text-sm sm:text-xs font-mono focus:outline-none"
                          >
                            <option value="Allow">Allow</option>
                            <option value="Disallow">Disallow</option>
                          </select>
                          <input
                            type="text"
                            value={rule.path}
                            onChange={(e) => updateRule(ua.id, rule.id, { path: e.target.value })}
                            className="flex-1 min-w-[120px] bg-transparent border border-[#141414] p-2 sm:p-1 text-sm sm:text-xs font-mono focus:outline-none"
                            placeholder="/path"
                          />
                          <button
                            onClick={() => removeRule(ua.id, rule.id)}
                            className="p-2 sm:p-1 hover:text-red-600 transition-colors"
                          >
                            <Trash2 size={16} className="sm:w-[12px] sm:h-[12px]" />
                          </button>
                        </div>
                      ))}
                    </div>
                    {ua.name !== '*' && (
                      <div className="mt-6 pt-4 border-t border-[#141414]/10 flex justify-end">
                        <button
                          onClick={() => removeUserAgent(ua.id)}
                          className="text-[9px] uppercase font-mono text-red-600 hover:bg-red-50 px-2 py-1 transition-colors flex items-center gap-1"
                        >
                          <Trash2 size={10} /> Delete Agent
                        </button>
                      </div>
                    )}
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </section>

          <section>
            <div className="flex items-center justify-between mb-6 border-b border-[#141414] pb-2">
              <h2 className="text-xs uppercase tracking-[0.2em] font-bold flex items-center gap-2">
                <Globe size={14} /> Sitemaps
              </h2>
              <button
                onClick={addSitemap}
                className="text-xs sm:text-[10px] uppercase font-mono border border-[#141414] px-3 py-1.5 sm:px-2 sm:py-1 hover:bg-[#141414] hover:text-[#E4E3E0] transition-colors flex items-center gap-1"
              >
                <Plus size={12} /> Add Sitemap
              </button>
            </div>
            <div className="space-y-3">
              {sitemaps.map((sitemap, index) => (
                <div key={index} className="flex flex-wrap sm:flex-nowrap gap-2 items-center">
                  <input
                    type="text"
                    value={sitemap}
                    onChange={(e) => updateSitemap(index, e.target.value)}
                    className="flex-1 min-w-[150px] bg-transparent border border-[#141414] p-2 text-xs font-mono focus:outline-none"
                    placeholder="https://example.com/sitemap.xml"
                  />
                  <button
                    onClick={() => removeSitemap(index)}
                    className="p-2 hover:text-red-600 transition-colors"
                  >
                    <Trash2 size={14} />
                  </button>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Preview Side */}
        <div id="preview-side" className="bg-[#141414] p-6 lg:p-8 overflow-y-auto lg:max-h-[calc(100vh-89px)] relative min-h-[400px] lg:min-h-0">
          <div className="flex items-center justify-between mb-4">
            <span className="text-[10px] uppercase font-mono text-[#E4E3E0] opacity-50 tracking-widest">Live Preview: robots.txt</span>
            <div className="flex gap-2">
              <div className="w-2 h-2 rounded-full bg-red-500/50" />
              <div className="w-2 h-2 rounded-full bg-yellow-500/50" />
              <div className="w-2 h-2 rounded-full bg-green-500/50" />
            </div>
          </div>
          <pre className="text-[#E4E3E0] font-mono text-sm leading-relaxed whitespace-pre-wrap break-all selection:bg-[#E4E3E0] selection:text-[#141414]">
            {generatedText}
          </pre>
        </div>
      </main>
    </div>
  );
}
