'use client';

import React, { useState, useEffect } from 'react';
import { Plus, Trash2, Copy, Download, FileText, Globe, User, Shield, AlertCircle, Check, Image as ImageIcon, Loader2, Code, Eye, Settings2, Zap, Sparkles, Layout, Info, ChevronRight, Search, ExternalLink } from 'lucide-react';
import { motion, AnimatePresence, LayoutGroup } from 'motion/react';

interface Rule {
  id: string;
  type: 'Allow' | 'Disallow';
  path: string;
}

interface UserAgent {
  id: string;
  name: string;
  rules: Rule[];
}

const NIKE_SWOOSH = `#                                                                                                    
#                 \`\`                                                                        \`\`\`.\`    
#               \`+/                                                                 \`\`.-/+o+:-.      
#             \`/mo                                                          \`\`.-:+syhdhs/-\`          
#            -hMd                                                    \`..:+oyhmNNmds/-\`               
#          \`oNMM/                                            \`\`.-/oyhdmMMMMNdy+:.                    
#         .hMMMM-                                     \`.-/+shdmNMMMMMMNdy+:.                         
#        :mMMMMM+                             \`.-:+sydmNMMMMMMMMMNmho:.\`                             
#       :NMMMMMMN:                    \`.-:/oyhmmNMMMMMMMMMMMNmho:.\`                                  
#      .NMMMMMMMMNy:\`          \`.-/oshdmNMMMMMMMMMMMMMMMmhs/-\`                                       
#      hMMMMMMMMMMMMmhysooosyhdmNMMMMMMMMMMMMMMMMMMmds/-\`                                            
#     .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+-.\`                                                
#     -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+-.\`                                                     
#     \`NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyo:.\`                                                          
#      /NMMMMMMMMMMMMMMMMMMMMMMMmho:.\`                                                               
#       .yNMMMMMMMMMMMMMMMMmhs/.\`                                                                    
#         ./shdmNNmmdhyo/-\`\`                                                                         
#              \`\`\`\`\`                 `;

export default function RobotsGenerator() {
  const [userAgents, setUserAgents] = useState<UserAgent[]>([
    {
      id: '1',
      name: '*',
      rules: [
        { id: 'r1', type: 'Disallow', path: '/admin' },
        { id: 'r2', type: 'Disallow', path: '/private' },
      ],
    },
  ]);
  const [sitemaps, setSitemaps] = useState<string[]>(['https://example.com/sitemap.xml']);
  const [header, setHeader] = useState('# Generated by Robots.txt Generator Pro');
  const [footer, setFooter] = useState(NIKE_SWOOSH);
  const [copied, setCopied] = useState(false);
  const [isGeneratingAscii, setIsGeneratingAscii] = useState(false);
  const [showPreviewOnMobile, setShowPreviewOnMobile] = useState(false);
  const [asciiWidth, setAsciiWidth] = useState(60);
  const [asciiInverted, setAsciiInverted] = useState(false);
  const [asciiContrast, setAsciiContrast] = useState(1.5);
  const [asciiDetailed, setAsciiDetailed] = useState(false);
  const [logoText, setLogoText] = useState('');
  const [activeTab, setActiveTab] = useState<'editor' | 'preview'>('editor');
  const [searchQuery, setSearchQuery] = useState('');
  const [isAsciiExpanded, setIsAsciiExpanded] = useState(false);
  const [isQuickAddExpanded, setIsQuickAddExpanded] = useState(true);
  const fileInputRef = React.useRef<HTMLInputElement>(null);

  const PRESETS = [
    {
      name: 'Standard SEO',
      description: 'Balanced rules for most websites',
      config: {
        userAgents: [
          {
            id: 'p1',
            name: '*',
            rules: [
              { id: 'pr1', type: 'Disallow', path: '/admin/' },
              { id: 'pr2', type: 'Disallow', path: '/api/' },
              { id: 'pr3', type: 'Allow', path: '/api/public/' },
            ],
          },
        ],
        sitemaps: ['https://example.com/sitemap.xml'],
      },
    },
    {
      name: 'Block AI Bots',
      description: 'Prevent AI crawlers from scraping',
      config: {
        userAgents: [
          {
            id: 'p2',
            name: 'GPTBot',
            rules: [{ id: 'pr4', type: 'Disallow', path: '/' }],
          },
          {
            id: 'p3',
            name: 'CCBot',
            rules: [{ id: 'pr5', type: 'Disallow', path: '/' }],
          },
          {
            id: 'p4',
            name: 'Google-Extended',
            rules: [{ id: 'pr6', type: 'Disallow', path: '/' }],
          },
        ],
        sitemaps: [],
      },
    },
    {
      name: 'WordPress Default',
      description: 'Optimized for WP installations',
      config: {
        userAgents: [
          {
            id: 'p5',
            name: '*',
            rules: [
              { id: 'pr7', type: 'Disallow', path: '/wp-admin/' },
              { id: 'pr8', type: 'Allow', path: '/wp-admin/admin-ajax.php' },
            ],
          },
        ],
        sitemaps: ['https://example.com/wp-sitemap.xml'],
      },
    },
  ];

  const applyPreset = (preset: typeof PRESETS[0]) => {
    setUserAgents(preset.config.userAgents as any);
    setSitemaps(preset.config.sitemaps);
  };

  const COMMON_AGENTS = [
    { name: 'Googlebot', description: 'Google search crawler' },
    { name: 'Bingbot', description: 'Microsoft search crawler' },
    { name: 'YandexBot', description: 'Yandex search crawler' },
    { name: 'DuckDuckBot', description: 'DuckDuckGo crawler' },
    { name: 'Baiduspider', description: 'Baidu search crawler' },
  ];

  const generateAscii = (source: HTMLImageElement | HTMLCanvasElement) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return '';

    const width = asciiWidth;
    const sourceWidth = source.width;
    const sourceHeight = source.height;
    const height = (sourceHeight / sourceWidth) * width * 0.5; // 0.5 to compensate for character aspect ratio
    canvas.width = width;
    canvas.height = height;

    ctx.drawImage(source, 0, 0, width, height);
    const imageData = ctx.getImageData(0, 0, width, height);
    const pixels = imageData.data;

    const charsStandard = '@%#*+=-:. ';
    const charsDetailed = '$@B%8&WM#*oahkbdpqwmZO0QLCJUYXzcvunxrjft/\\|()1{}[]?-_+~<>i!lI;:,"^`\'. ';
    
    let chars = asciiDetailed ? charsDetailed : charsStandard;
    if (asciiInverted) {
      chars = chars.split('').reverse().join('');
    }

    let ascii = '';

    for (let i = 0; i < pixels.length; i += 4) {
      const r = pixels[i];
      const g = pixels[i + 1];
      const b = pixels[i + 2];
      const a = pixels[i + 3];

      // If transparent, use space
      if (a < 50) {
        ascii += ' ';
      } else {
        // Perceptual grayscale
        let brightness = (0.2126 * r + 0.7152 * g + 0.0722 * b);
        
        // Apply contrast
        brightness = ((brightness - 128) * asciiContrast) + 128;
        brightness = Math.max(0, Math.min(255, brightness));

        const charIndex = Math.floor((brightness / 255) * (chars.length - 1));
        ascii += chars[charIndex];
      }

      if ((i / 4 + 1) % width === 0) {
        ascii += '\n';
      }
    }

    // Add # to each line, preserving leading spaces for shape integrity
    return ascii.split('\n').map(line => `# ${line}`).join('\n');
  };

  const handleLogoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsGeneratingAscii(true);
    const reader = new FileReader();
    reader.onload = (event) => {
      const img = new Image();
      img.onload = () => {
        const ascii = generateAscii(img);
        setFooter(ascii);
        setIsGeneratingAscii(false);
      };
      img.src = event.target?.result as string;
    };
    reader.readAsDataURL(file);
  };

  const generateAsciiFromText = () => {
    if (!logoText) return;
    setIsGeneratingAscii(true);
    
    // Use a temporary canvas to render text
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const fontSize = 60;
    ctx.font = `bold ${fontSize}px monospace`;
    const metrics = ctx.measureText(logoText);
    
    canvas.width = Math.ceil(metrics.width) + 20;
    canvas.height = fontSize + 20;

    // Background
    ctx.fillStyle = 'white';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // Text
    ctx.fillStyle = 'black';
    ctx.font = `bold ${fontSize}px monospace`;
    ctx.textBaseline = 'middle';
    ctx.textAlign = 'center';
    ctx.fillText(logoText, canvas.width / 2, canvas.height / 2);

    const ascii = generateAscii(canvas);
    setFooter(ascii);
    setIsGeneratingAscii(false);
  };

  const filteredAgents = React.useMemo(() => {
    if (!searchQuery) return userAgents;
    return userAgents.filter(ua => 
      ua.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      ua.rules.some(r => r.path.toLowerCase().includes(searchQuery.toLowerCase()))
    );
  }, [userAgents, searchQuery]);

  const renderHighlightedText = (text: string) => {
    return text.split('\n').map((line, i) => {
      if (line.startsWith('#')) return <span key={i} className="text-white/30 italic">{line}{'\n'}</span>;
      if (line.startsWith('User-agent:')) {
        const parts = line.split(': ');
        const label = parts[0];
        const value = parts.slice(1).join(': ');
        return <span key={i}><span className="text-[#FFBD2E] font-bold">{label}:</span> <span className="text-white">{value}</span>{'\n'}</span>;
      }
      if (line.startsWith('Allow:') || line.startsWith('Disallow:')) {
        const parts = line.split(': ');
        const label = parts[0];
        const value = parts.slice(1).join(': ');
        return <span key={i}><span className={label === 'Allow' ? 'text-[#27C93F]' : 'text-[#FF5F56]'}>{label}:</span> <span className="text-white/80">{value}</span>{'\n'}</span>;
      }
      if (line.startsWith('Sitemap:')) {
        const parts = line.split(': ');
        const label = parts[0];
        const value = parts.slice(1).join(': ');
        return <span key={i}><span className="text-[#3B82F6]">{label}:</span> <span className="text-white/60 underline decoration-white/20">{value}</span>{'\n'}</span>;
      }
      return <span key={i} className="text-white/80">{line}{'\n'}</span>;
    });
  };

  const generatedText = React.useMemo(() => {
    let text = header ? `${header}\n\n` : '';

    userAgents.forEach((ua) => {
      text += `User-agent: ${ua.name}\n`;
      ua.rules.forEach((rule) => {
        text += `${rule.type}: ${rule.path}\n`;
      });
      text += '\n';
    });

    sitemaps.forEach((sitemap) => {
      text += `Sitemap: ${sitemap}\n`;
    });

    if (footer) {
      text += `\n${footer}`;
    }

    return text;
  }, [userAgents, sitemaps, header, footer]);

  const addUserAgent = (name: string = 'New-Agent') => {
    setUserAgents([
      ...userAgents,
      { id: Math.random().toString(36).substr(2, 9), name, rules: [] },
    ]);
  };

  const removeUserAgent = (id: string) => {
    const agent = userAgents.find(ua => ua.id === id);
    if (agent?.name === '*') return;
    setUserAgents(userAgents.filter((ua) => ua.id !== id));
  };

  const updateUserAgentName = (id: string, name: string) => {
    setUserAgents(userAgents.map((ua) => (ua.id === id ? { ...ua, name } : ua)));
  };

  const addRule = (uaId: string) => {
    setUserAgents(
      userAgents.map((ua) => {
        if (ua.id === uaId) {
          return {
            ...ua,
            rules: [
              ...ua.rules,
              { id: Math.random().toString(36).substr(2, 9), type: 'Disallow', path: '/' },
            ],
          };
        }
        return ua;
      })
    );
  };

  const removeRule = (uaId: string, ruleId: string) => {
    setUserAgents(
      userAgents.map((ua) => {
        if (ua.id === uaId) {
          return { ...ua, rules: ua.rules.filter((r) => r.id !== ruleId) };
        }
        return ua;
      })
    );
  };

  const updateRule = (uaId: string, ruleId: string, updates: Partial<Rule>) => {
    setUserAgents(
      userAgents.map((ua) => {
        if (ua.id === uaId) {
          return {
            ...ua,
            rules: ua.rules.map((r) => (r.id === ruleId ? { ...r, ...updates } : r)),
          };
        }
        return ua;
      })
    );
  };

  const clearAllAgents = () => {
    if (window.confirm('Are you sure you want to clear all agents? This will reset to default.')) {
      setUserAgents([{ id: '1', name: '*', rules: [{ id: 'r1', type: 'Disallow', path: '/admin' }, { id: 'r2', type: 'Disallow', path: '/private' }] }]);
    }
  };

  const resetAll = () => {
    if (window.confirm('Reset everything to default settings?')) {
      setUserAgents([{ id: '1', name: '*', rules: [{ id: 'r1', type: 'Disallow', path: '/admin' }, { id: 'r2', type: 'Disallow', path: '/private' }] }]);
      setSitemaps(['https://example.com/sitemap.xml']);
      setHeader('# Generated by Robots.txt Generator Pro');
      setFooter(NIKE_SWOOSH);
      setLogoText('');
    }
  };

  const removeSitemap = (index: number) => {
    setSitemaps(sitemaps.filter((_, i) => i !== index));
  };

  const updateSitemap = (index: number, value: string) => {
    const newSitemaps = [...sitemaps];
    newSitemaps[index] = value;
    setSitemaps(newSitemaps);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadFile = () => {
    const element = document.createElement('a');
    const file = new Blob([generatedText], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = 'robots.txt';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const openInNewTab = () => {
    const blob = new Blob([generatedText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
  };

  return (
    <div id="tool" className="min-h-screen bg-[#F5F5F4] text-[#141414] font-sans selection:bg-[#141414] selection:text-[#F5F5F4] relative flex flex-col">
      {/* Mobile Header */}
      <header className="lg:hidden bg-white border-b border-[#141414] p-4 flex items-center justify-between sticky top-0 z-50">
        <h1 className="text-xs font-bold uppercase tracking-widest flex items-center gap-2">
          <Shield size={16} /> Robots.txt Pro
        </h1>
        <div className="flex gap-2">
          <button onClick={copyToClipboard} className="p-2 border border-[#141414] rounded-sm">
            {copied ? <Check size={16} className="text-green-600" /> : <Copy size={16} />}
          </button>
          <button onClick={downloadFile} className="p-2 bg-[#141414] text-white rounded-sm">
            <Download size={16} />
          </button>
        </div>
      </header>

      <main className="flex-1 grid grid-cols-1 lg:grid-cols-[7fr_3fr] overflow-hidden">
        {/* Editor Side */}
        <div 
          id="editor-side" 
          className={`p-4 lg:p-8 overflow-y-auto lg:max-h-[calc(100vh-89px)] ${activeTab === 'preview' ? 'hidden lg:block' : 'block'}`}
        >
          <div className="max-w-5xl mx-auto space-y-6 pb-24 lg:pb-0">
            {/* Presets Grid */}
            <section className="flex items-center justify-between gap-4 bg-white border border-[#141414]/5 p-2 px-4 shadow-sm rounded-sm">
              <div className="flex items-center gap-3">
                <h3 className="text-[8px] uppercase tracking-[0.2em] font-black opacity-20 whitespace-nowrap">Presets:</h3>
                <div className="flex gap-2">
                  {PRESETS.map((preset) => (
                    <button
                      key={preset.name}
                      onClick={() => applyPreset(preset)}
                      className="group relative px-3 py-1 bg-[#F5F5F4] border border-[#141414]/5 hover:border-[#141414] hover:bg-[#141414] hover:text-white transition-all text-[9px] font-bold uppercase tracking-wider"
                    >
                      {preset.name}
                    </button>
                  ))}
                </div>
              </div>
              <button 
                onClick={resetAll}
                className="text-[8px] uppercase font-bold text-red-600/30 hover:text-red-600 transition-all"
              >
                Reset All
              </button>
            </section>

            <div className="grid grid-cols-1 xl:grid-cols-12 gap-6">
              {/* Left Column: Global & Sitemaps */}
              <div className="xl:col-span-5 space-y-6">
                {/* Global Config Card */}
                <section className="bg-white border border-[#141414] p-5 shadow-sm">
                  <div className="flex items-center justify-between mb-5 border-b border-[#141414]/5 pb-3">
                    <h2 className="text-[9px] uppercase tracking-[0.3em] font-black flex items-center gap-2 opacity-60">
                      <Settings2 size={12} /> 01. Global
                    </h2>
                    <div className="hidden lg:flex gap-2">
                      <button
                        onClick={copyToClipboard}
                        className="flex items-center gap-2 px-3 py-1 border border-[#141414] hover:bg-[#141414] hover:text-white transition-all text-[10px] font-mono uppercase tracking-wider"
                      >
                        {copied ? <Check size={12} /> : <Copy size={12} />}
                        {copied ? 'Copied' : 'Copy'}
                      </button>
                    </div>
                  </div>

                  <div className="space-y-6">
                    <div>
                      <label className="text-[9px] uppercase font-bold opacity-30 block mb-1.5 tracking-widest">Header Comment</label>
                      <input
                        type="text"
                        value={header}
                        onChange={(e) => setHeader(e.target.value)}
                        className="w-full bg-[#F5F5F4] border border-[#141414]/10 p-2.5 font-mono text-xs focus:border-[#141414] focus:outline-none transition-all"
                        placeholder="# Enter header comment..."
                      />
                    </div>

                    <div className="space-y-4 pt-4 border-t border-[#141414]/5">
                      <button 
                        onClick={() => setIsAsciiExpanded(!isAsciiExpanded)}
                        className="w-full flex items-center justify-between group py-1"
                      >
                        <div className="flex items-center gap-2">
                          <label className="text-[10px] uppercase font-bold opacity-50 tracking-widest cursor-pointer group-hover:opacity-100 transition-opacity">ASCII Logo & Branding</label>
                          {!isAsciiExpanded && <Sparkles size={10} className="text-[#FFBD2E] animate-pulse" />}
                        </div>
                        <ChevronRight size={14} className={`opacity-30 transition-transform duration-300 ${isAsciiExpanded ? 'rotate-90' : ''}`} />
                      </button>
                      
                      <AnimatePresence>
                        {isAsciiExpanded && (
                          <motion.div 
                            initial={{ height: 0, opacity: 0 }}
                            animate={{ height: 'auto', opacity: 1 }}
                            exit={{ height: 0, opacity: 0 }}
                            className="overflow-hidden space-y-4"
                          >
                            <div className="flex gap-1 justify-end">
                              <button 
                                onClick={() => setAsciiDetailed(!asciiDetailed)} 
                                className={`text-[9px] font-bold border border-[#141414] px-2 py-1 transition-colors ${asciiDetailed ? 'bg-[#141414] text-white' : 'hover:bg-[#141414]/5'}`}
                              >
                                HD
                              </button>
                              <button 
                                onClick={() => setAsciiInverted(!asciiInverted)} 
                                className={`text-[9px] font-bold border border-[#141414] px-2 py-1 transition-colors ${asciiInverted ? 'bg-[#141414] text-white' : 'hover:bg-[#141414]/5'}`}
                              >
                                INV
                              </button>
                            </div>

                            <div className="space-y-3">
                              <div className="flex gap-2">
                                <input
                                  type="text"
                                  value={logoText}
                                  onChange={(e) => setLogoText(e.target.value)}
                                  placeholder="Type text for logo..."
                                  className="flex-1 bg-[#F5F5F4] border border-[#141414] p-2.5 font-mono text-xs focus:outline-none"
                                />
                                <button
                                  onClick={generateAsciiFromText}
                                  disabled={!logoText}
                                  className="bg-[#141414] text-white px-4 py-1 text-[10px] uppercase font-bold font-mono hover:bg-[#333] transition-colors disabled:opacity-50"
                                >
                                  Generate
                                </button>
                              </div>
                              <button
                                onClick={() => fileInputRef.current?.click()}
                                className="w-full flex items-center justify-center gap-3 border-2 border-[#141414] p-3 text-[10px] uppercase font-black tracking-widest hover:bg-[#141414] hover:text-white transition-all active:scale-[0.98]"
                              >
                                {isGeneratingAscii ? <Loader2 size={14} className="animate-spin" /> : <ImageIcon size={14} />}
                                Upload Image Logo
                              </button>
                              <input type="file" ref={fileInputRef} onChange={handleLogoUpload} accept="image/*" className="hidden" />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                              <div className="bg-[#F5F5F4] border border-[#141414] p-3">
                                <div className="flex justify-between items-center mb-2">
                                  <span className="text-[8px] uppercase font-black opacity-40 tracking-tighter">Width</span>
                                  <span className="text-[10px] font-mono font-bold">{asciiWidth}px</span>
                                </div>
                                <input type="range" min="20" max="100" value={asciiWidth} onChange={(e) => setAsciiWidth(Number(e.target.value))} className="w-full h-1 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-[#141414]" />
                              </div>
                              <div className="bg-[#F5F5F4] border border-[#141414] p-3">
                                <div className="flex justify-between items-center mb-2">
                                  <span className="text-[8px] uppercase font-black opacity-40 tracking-tighter">Contrast</span>
                                  <span className="text-[10px] font-mono font-bold">{asciiContrast}x</span>
                                </div>
                                <input type="range" min="0" max="4" step="0.1" value={asciiContrast} onChange={(e) => setAsciiContrast(Number(e.target.value))} className="w-full h-1 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-[#141414]" />
                              </div>
                            </div>

                            <div className="relative group">
                              <textarea
                                value={footer}
                                onChange={(e) => setFooter(e.target.value)}
                                rows={8}
                                className="w-full bg-[#141414] text-[#E4E3E0] p-4 font-mono text-[10px] leading-tight focus:outline-none resize-none scrollbar-thin scrollbar-thumb-white/10"
                              />
                              <button 
                                onClick={() => setFooter('')}
                                className="absolute top-2 right-2 p-1.5 bg-white/5 hover:bg-white/20 text-white/40 hover:text-white rounded transition-all opacity-0 group-hover:opacity-100"
                                title="Clear ASCII"
                              >
                                <Trash2 size={12} />
                              </button>
                            </div>
                          </motion.div>
                        )}
                      </AnimatePresence>
                    </div>
                  </div>
                </section>

                {/* Sitemaps Card */}
                <section className="bg-white border border-[#141414]/10 p-5 shadow-sm">
                  <div className="flex items-center justify-between mb-5 border-b border-[#141414]/5 pb-3">
                    <h2 className="text-[9px] uppercase tracking-[0.3em] font-black flex items-center gap-2 opacity-60">
                      <Globe size={12} /> 03. Sitemaps
                    </h2>
                    <div className="flex gap-2">
                      <button 
                        onClick={() => setSitemaps([])} 
                        className="text-[8px] font-bold uppercase opacity-20 hover:opacity-100 transition-opacity hover:text-red-600 px-2"
                      >
                        Clear
                      </button>
                      <button 
                        onClick={() => setSitemaps([...sitemaps, 'https://example.com/sitemap.xml'])} 
                        className="bg-[#141414] text-white p-1 rounded-sm hover:scale-105 transition-transform"
                      >
                        <Plus size={14} />
                      </button>
                    </div>
                  </div>
                  <div className="space-y-2">
                    {sitemaps.map((sitemap, index) => (
                      <div key={index} className="flex gap-2 items-center group">
                        <div className="relative flex-1">
                          <input
                            type="text"
                            value={sitemap}
                            onChange={(e) => updateSitemap(index, e.target.value)}
                            className={`w-full bg-[#F5F5F4] border ${sitemap.startsWith('http') ? 'border-[#141414]/10' : 'border-red-500/50'} p-2 text-[10px] font-mono focus:outline-none focus:border-[#141414] transition-all`}
                            placeholder="https://..."
                          />
                          {!sitemap.startsWith('http') && (
                            <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1 text-red-500">
                              <span className="text-[7px] font-bold uppercase">Invalid</span>
                              <AlertCircle size={10} />
                            </div>
                          )}
                        </div>
                        <button onClick={() => removeSitemap(index)} className="opacity-0 group-hover:opacity-100 p-1.5 text-red-600/40 hover:text-red-600 transition-all">
                          <Trash2 size={14} />
                        </button>
                      </div>
                    ))}
                    {sitemaps.length === 0 && (
                      <div className="flex flex-col items-center justify-center py-6 border border-dashed border-[#141414]/10 rounded bg-[#F5F5F4]/50">
                        <Globe size={20} className="opacity-10 mb-2" />
                        <p className="text-[9px] font-bold opacity-20 uppercase tracking-widest">No sitemaps</p>
                      </div>
                    )}
                  </div>
                </section>
              </div>

              {/* Right Column: User Agents */}
              <div className="xl:col-span-7 space-y-6">
                <section className="bg-white border border-[#141414] p-5 shadow-sm h-full flex flex-col">
                  <div className="flex items-center justify-between mb-5 border-b border-[#141414]/5 pb-3">
                    <h2 className="text-[9px] uppercase tracking-[0.3em] font-black flex items-center gap-2 opacity-60">
                      <User size={12} /> 02. Rules
                    </h2>
                    <div className="flex gap-2">
                      <div className="relative hidden sm:block">
                        <Search size={12} className="absolute left-2.5 top-1/2 -translate-y-1/2 opacity-20" />
                        <input 
                          type="text" 
                          placeholder="Filter..." 
                          value={searchQuery}
                          onChange={(e) => setSearchQuery(e.target.value)}
                          className="bg-[#F5F5F4] border border-[#141414]/10 pl-8 pr-3 py-1 text-[10px] font-mono focus:outline-none w-32 transition-all focus:w-48 focus:border-[#141414]"
                        />
                      </div>
                      <button 
                        onClick={clearAllAgents} 
                        className="text-[8px] font-bold uppercase opacity-30 hover:opacity-100 transition-opacity hover:text-red-600 px-2"
                      >
                        Clear
                      </button>
                      <button
                        onClick={() => addUserAgent()}
                        className="bg-[#141414] text-white px-3 py-1 text-[9px] uppercase font-black tracking-widest flex items-center gap-1.5 hover:bg-[#333] transition-all active:scale-95"
                      >
                        <Plus size={12} /> Add Agent
                      </button>
                    </div>
                  </div>

                  <div className="mb-8 border border-[#141414]/10 rounded overflow-hidden">
                    <button 
                      onClick={() => setIsQuickAddExpanded(!isQuickAddExpanded)}
                      className="w-full bg-[#F5F5F4] p-4 flex items-center justify-between group hover:bg-[#141414]/5 transition-colors"
                    >
                      <div className="flex items-center gap-2">
                        <label className="text-[10px] uppercase font-black opacity-40 tracking-[0.2em] cursor-pointer">Quick Add Popular Bots</label>
                        <div className="group relative">
                          <Info size={12} className="opacity-30 cursor-help" />
                          <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-48 p-2 bg-[#141414] text-white text-[9px] rounded opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-20">
                            Click to quickly add specific rules for these popular crawlers.
                          </div>
                        </div>
                      </div>
                      <ChevronRight size={14} className={`opacity-30 transition-transform duration-300 ${isQuickAddExpanded ? 'rotate-90' : ''}`} />
                    </button>
                    
                    <AnimatePresence>
                      {isQuickAddExpanded && (
                        <motion.div 
                          initial={{ height: 0, opacity: 0 }}
                          animate={{ height: 'auto', opacity: 1 }}
                          exit={{ height: 0, opacity: 0 }}
                          className="overflow-hidden bg-white p-4"
                        >
                          <div className="flex flex-wrap gap-2">
                            {COMMON_AGENTS.map(agent => (
                              <button
                                key={agent.name}
                                onClick={() => addUserAgent(agent.name)}
                                className="text-[10px] font-mono font-bold border-2 border-[#141414] px-3 py-1 hover:bg-[#141414] hover:text-white transition-all active:translate-y-0.5"
                              >
                                {agent.name}
                              </button>
                            ))}
                          </div>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>

                  <div className="space-y-4 flex-1 overflow-y-auto pr-2 custom-scrollbar">
                    <LayoutGroup>
                      <AnimatePresence mode="popLayout">
                        {filteredAgents.length === 0 ? (
                          <div className="flex flex-col items-center justify-center py-12 opacity-20">
                            <Search size={32} strokeWidth={1} />
                            <p className="text-[10px] uppercase tracking-widest mt-4">No agents found</p>
                          </div>
                        ) : (
                          filteredAgents.map((ua) => (
                            <motion.div
                              key={ua.id}
                              layout
                              initial={{ opacity: 0, y: 10 }}
                              animate={{ opacity: 1, y: 0 }}
                              exit={{ opacity: 0, scale: 0.95 }}
                              className="border border-[#141414]/10 p-4 bg-white group mb-4 hover:border-[#141414]/30 transition-all"
                            >
                              <div className="flex items-center justify-between mb-5">
                                <div className="flex-1 flex items-center gap-3">
                                  <span className="text-[9px] font-black opacity-20 tracking-widest">AGENT</span>
                                  <input
                                    type="text"
                                    value={ua.name}
                                    onChange={(e) => updateUserAgentName(ua.id, e.target.value)}
                                    className="flex-1 bg-transparent border-b border-[#141414]/10 pb-0.5 font-black text-lg focus:outline-none focus:border-[#141414] transition-colors"
                                    placeholder="*"
                                  />
                                </div>
                                <div className="flex items-center gap-1">
                                  <button 
                                    onClick={() => {
                                      const agentText = `User-agent: ${ua.name}\n${ua.rules.map(r => `${r.type}: ${r.path}`).join('\n')}`;
                                      navigator.clipboard.writeText(agentText);
                                    }}
                                    className="p-1.5 text-[#141414]/20 hover:text-[#141414] transition-colors"
                                    title="Copy agent"
                                  >
                                    <Copy size={14} />
                                  </button>
                                  {ua.name !== '*' && (
                                    <button onClick={() => removeUserAgent(ua.id)} className="opacity-0 group-hover:opacity-100 p-1.5 text-red-600/40 hover:text-red-600 transition-all">
                                      <Trash2 size={16} />
                                    </button>
                                  )}
                                </div>
                              </div>

                              <div className="space-y-2">
                                {ua.rules.map((rule) => (
                                  <motion.div key={rule.id} layout className="flex gap-2 items-center">
                                    <select
                                      value={rule.type}
                                      onChange={(e) => updateRule(ua.id, rule.id, { type: e.target.value as any })}
                                      className="bg-[#F5F5F4] border border-[#141414]/10 p-1.5 text-[9px] font-bold focus:outline-none focus:border-[#141414] transition-all"
                                    >
                                      <option value="Allow">ALLOW</option>
                                      <option value="Disallow">BLOCK</option>
                                    </select>
                                    <div className="relative flex-1">
                                      <input
                                        type="text"
                                        value={rule.path}
                                        onChange={(e) => updateRule(ua.id, rule.id, { path: e.target.value })}
                                        className={`w-full bg-[#F5F5F4] border ${rule.path.startsWith('/') ? 'border-[#141414]/10' : 'border-red-500/50'} p-1.5 text-[10px] font-mono focus:outline-none focus:border-[#141414] transition-all`}
                                        placeholder="/path"
                                      />
                                      {!rule.path.startsWith('/') && (
                                        <AlertCircle size={10} className="absolute right-2 top-1/2 -translate-y-1/2 text-red-500" />
                                      )}
                                    </div>
                                    <button onClick={() => removeRule(ua.id, rule.id)} className="p-1.5 text-red-600/20 hover:text-red-600 transition-all">
                                      <Trash2 size={12} />
                                    </button>
                                  </motion.div>
                                ))}
                                <button
                                  onClick={() => addRule(ua.id)}
                                  className="w-full py-2 border border-dashed border-[#141414]/10 text-[9px] font-bold uppercase tracking-widest text-[#141414]/30 hover:text-[#141414] hover:border-[#141414]/30 hover:bg-[#F5F5F4] transition-all mt-2"
                                >
                                  + Add Rule
                                </button>
                              </div>
                            </motion.div>
                          ))
                        )}
                      </AnimatePresence>
                    </LayoutGroup>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>

        {/* Preview Side */}
        <div 
          id="preview-side" 
          className={`bg-[#141414] p-4 lg:p-12 overflow-y-auto lg:max-h-[calc(100vh-89px)] relative ${activeTab === 'editor' ? 'hidden lg:block' : 'block'}`}
        >
          <div className="max-w-3xl mx-auto">
            <div className="flex items-center justify-between mb-8 border-b border-white/10 pb-4 sticky top-0 bg-[#141414] z-10 pt-2">
              <div className="flex items-center gap-3">
                <div className="flex gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full bg-[#FF5F56]" />
                  <div className="w-2.5 h-2.5 rounded-full bg-[#FFBD2E]" />
                  <div className="w-2.5 h-2.5 rounded-full bg-[#27C93F]" />
                </div>
                <span className="text-[10px] font-mono text-white/40 uppercase tracking-[0.2em]">robots.txt — Live Preview</span>
              </div>
              <div className="flex gap-4">
                <button onClick={copyToClipboard} className="text-white/40 hover:text-white transition-colors flex items-center gap-2 text-[10px] font-mono uppercase">
                  {copied ? <Check size={12} className="text-green-500" /> : <Copy size={12} />}
                  {copied ? 'Copied' : 'Copy'}
                </button>
                <button onClick={openInNewTab} className="text-white/40 hover:text-white transition-colors flex items-center gap-2 text-[10px] font-mono uppercase" title="Open in new tab">
                  <ExternalLink size={12} />
                  Full
                </button>
                <button onClick={downloadFile} className="text-white/40 hover:text-white transition-colors flex items-center gap-2 text-[10px] font-mono uppercase">
                  <Download size={12} />
                  Save
                </button>
              </div>
            </div>

            <div className="flex font-mono text-xs sm:text-sm">
              <div className="pr-6 border-r border-white/10 text-white/20 select-none text-right hidden sm:block font-bold">
                {generatedText.split('\n').map((_, i) => (
                  <div key={i} className="h-6 leading-6">{i + 1}</div>
                ))}
              </div>
              <pre className="pl-6 text-[#E4E3E0] leading-6 whitespace-pre-wrap break-all selection:bg-white selection:text-[#141414] flex-1">
                {renderHighlightedText(generatedText)}
              </pre>
            </div>
          </div>
        </div>
      </main>

      {/* Mobile Navigation Tabs */}
      <nav className="lg:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-[#141414] grid grid-cols-2 z-50">
        <button 
          onClick={() => setActiveTab('editor')}
          className={`flex flex-col items-center justify-center p-3 gap-1 transition-all ${activeTab === 'editor' ? 'bg-[#141414] text-white' : 'text-[#141414]'}`}
        >
          <Code size={18} />
          <span className="text-[9px] font-bold uppercase tracking-widest">Editor</span>
        </button>
        <button 
          onClick={() => setActiveTab('preview')}
          className={`flex flex-col items-center justify-center p-3 gap-1 transition-all ${activeTab === 'preview' ? 'bg-[#141414] text-white' : 'text-[#141414]'}`}
        >
          <Eye size={18} />
          <span className="text-[9px] font-bold uppercase tracking-widest">Preview</span>
        </button>
      </nav>
    </div>
  );
}
